### PR TITLE
6.0.0 actual

### PR DESCRIPTION
**Pull request by paulpv**
This is an aggregate of the following **already reviewed** PRs to https://github.com/DistroAV/DistroAV/tree/6.0.0_actual:
* https://github.com/DistroAV/DistroAV/pull/1044 Merged
* https://github.com/DistroAV/DistroAV/pull/1045 Merged
* https://github.com/DistroAV/DistroAV/pull/1055 Merged
* https://github.com/DistroAV/DistroAV/pull/1057 Merged
* https://github.com/DistroAV/DistroAV/pull/1062 Merged
* https://github.com/DistroAV/DistroAV/pull/1066 Merged

Plus these changes:
* https://github.com/DistroAV/DistroAV/pull/1050/commits/581efae1ac2cc58583480e44f4d43195f4691830
* https://github.com/DistroAV/DistroAV/pull/1050/commits/e097489cda1bc27d703e637c7d344f3b6e3c892b

### CODE REVIEW

**Comment by paulpv** [comment]
@Trouffman The main 6.0 PR, ready for review, but it has already been reviewed and approved in at least 4 parts.

The real intent of this is now to get a Seeking Testers build and have a few people try out its functionality.

After this gets vetted I then would like to try a "Pre-Release" release, which will have it show up on the Releases page, but not on https://github.com/DistroAV/DistroAV/releases/latest or https://api.github.com/repos/DistroAV/DistroAV/releases/latest

Then more people can test this out a little easier.

Then in ~1-2 weeks, if there are no big issues, we can officially release it.

CC @RayneYoruka @Palakis

**Comment by RayneYoruka** [comment]
I'll start testing during daytime

**Comment by Trouffman** [comment]
Procees makes sense, I will be giving it a run.

**Comment by paulpv** [comment]
@Trouffman @RayneYoruka 
The builds for this are available in the Summary of the build status for this branch/PR.
(currently https://github.com/DistroAV/DistroAV/actions/runs/10224340836)

**Comment by paulpv** [comment]
I am thinking, **if all of our testing goes ok**, of merging and creating a pre-Release release on Monday.

**Comment by paulpv** [comment]
First experience with DistroAV 6.0 on MacOS:
image

☹️

**Comment by paulpv** [comment]
This is probably related to me changing the package name from `fr.palakis.obs-ndi` to `org.distroav.distroav`:
https://github.com/DistroAV/DistroAV/pull/1050/files#diff-d377ff3be1e2b9fd31f995cedd4b8d7a4b9f64a9e7493b7004e30ef7fc309b99R48

@Palakis , any experience with this?  
Is this something we can change in the Apple Developer account?

**Comment by paulpv** [comment]
Merged @BitRate27 's GUID and typo changes.

New build will be available at https://github.com/DistroAV/DistroAV/actions/runs/10231355580

**Comment by paulpv** [comment]
New build at the bottom of https://github.com/DistroAV/DistroAV/actions/runs/10231694771 that changes the `Uninstall OBS-NDI` link to https://distroav.org/kb/uninstall-obs-ndi

**Comment by paulpv** [comment]
I was hoping the new Mac GUIDs might kick this into start working.
image
Looks like my employer prevents me from allowing unidentified apps.
Maybe I will look into creating a DistroAV Apple Developer account now (instead of waiting until @Palakis' current one expires May 2025)

**Comment by paulpv** [comment]
Ha! Running `sudo spctl --master-disable` on my Mac got me to bypass my employer's security policy :)

**Comment by paulpv** [comment]
MacOS DistroAV 6.0 installs and works fine for me.  
It detects OBS-NDI and says to uninstall OBS-NDI (link to https://distroav.org/kb/uninstall-obs-ndi) and unloads.  
Uninstall OBS-NDI (`rm -r -f ~/Library/Application\ Support/obs-studio/plugins/obs-ndi.*`). 
Launch OBS and DIstroAV works fine.

Known issue about update checking results in 404; only [official] releases with hashes added to the update server will get a successful result.

So, I'm about 36 hours from merging this PR and creating a pre-release build to be available to anyone who wants to try it early and give us feedback of anything we missed.

Anyone have any concerns to not do this?

**Comment by RayneYoruka** [comment]
With the 3 hours of test that I've given it without issues I think it's a good idea to make it a pre-release and let anyone test it. This way we will narrow if there is any issues in any scenario. I will do a few more tests as well today.

On the mean time @Trouffman can work on the disconnect when not vissible (https://github.com/DistroAV/DistroAV/issues/1064)

**Comment by RayneYoruka** [comment]
Will test again in a few days and see if I see any issues.. anything specific I should be looking for?

**Comment by paulpv** [comment]
> anything specific I should be looking for?

Uh... Everything? :)

I think it is finally ready enough for the planned "pre-release".

I can push that out and you can use its release notes summary as some things to focus on.

**Comment by paulpv** [comment]
This PR is huge, but everything major change in it has gone through multiple smaller PRs that were reviewed. 

I am going to merge this and create a pre-release of 6.0.

We may still make some last minute changes to Behavior before final release.

**Comment by RayneYoruka** [comment]
> I can push that out and you can use its release notes summary as some things to focus on.

Sounds good, this way I'll be able to test everything one by one

**Comment by RayneYoruka** [comment]
It seems the 6.0.0 release does not detect the NDI runtime while installing on a portable install of obs. This seems to happen to an user on the discord server. Should look in to it

**Pull request merged**
