### PR TITLE
source: NDI5+ hardware acceleration

### PR DESCRIPTION
**Pull request by paulpv**
NDI5 changed the hardware acceleration request from `<ndi_hwaccel enabled="true"/>` to `<ndi_video_codec type="hardware"/>`.
We've never updated our code,
I'm updating our code. :)

Adding a long extensive comment in the code.

See also:
* https://docs.ndi.video/docs/sdk/performance-and-implementation#receiving-video
* https://forum.vizrt.com/index.php?threads/is-ndi_hwaccel-still-supported.251864/
* https://github.com/DistroAV/DistroAV/issues/664

### CODE REVIEW

**Comment by paulpv** [comment]
@Trouffman As mentioned in Discord, this "feature" is a little silly and never worked in NDI5 and somehow we survived.

Options:
1. Use this PR's code as written when sends a working metadata when `Allow hardware acceleration` is checked and send a fake non-working metadata when it is unchecked.
2. Change this PR's code to only send the working documented metadata only when the `Allow hardware acceleration` is checked (ie: don't send a fake non-working metadata).
3. Not have any UI option and just always send a request to enable hardware acceleration.

I think an option is best.  
I could see some users wanting to legitimately reserve all of their GPU compute for gaming/whatever and not wanting any of their GPU used by NDI.

**Comment by Trouffman** [comment]
Option 2.

**Comment by paulpv** [comment]
I am tempted to turn this on by default, but I do not think that we should because [I think] the only way to directly turn this off for someone who does not want this enabled.

The only way I can think of to turn this off is to maybe reset the receiver, which is not intuitive how to do.  
We could make it so that **any** settings change stops and restarts the receiver.

One other way is to require the user to close and reopen OBS! 😦

**Comment by Trouffman** [comment]
"Forcing" a receiver reset on a  settings change could be the way, this is already the case for some of them.

**Comment by paulpv** [comment]
> "Forcing" a receiver reset on a settings change could be the way, this is already the case for some of them.

I have a solution for that in another PR, so I will go ahead and merge this relatively tiny PR.

**Pull request merged**
